CostManager/Models/Database/Usuario.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CostManager.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Endereco = new HashSet<Endereco>();
            this.Telefone = new HashSet<Telefone>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public string CPF { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public int Perfil { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Endereco> Endereco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefone> Telefone { get; set; }
    }
}

CostManager/Models/ViewModel/UsuarioViewModel.cs
using CostManager.Models.Database;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CostManager.Models.ViewModel
{
    public class UsuarioViewModel
    {
        [DisplayName("Nome")]
        [Required(ErrorMessage = "O nome é obrigatório")]
        [StringLength(250, MinimumLength = 3, ErrorMessage = "O nome deve ter entre 3 e 250 caracteres")]
        public string Nome { get; set; } = string.Empty;

        [DisplayName("E-mail")]
        [Required(ErrorMessage = "O e-mail é obrigatório")]
        [EmailAddress(ErrorMessage = "E-mail inválido")]
        [StringLength(250, MinimumLength = 3, ErrorMessage = "O e-mail deve ter entre 3 e 250 caracteres")]
        public string Email { get; set; } = string.Empty;

        [DisplayName("CPF")]
        [Required(ErrorMessage = "O CPF é obrigatório")]
        [StringLength(20, MinimumLength = 11, ErrorMessage = "O CPF deve ter 11 caracteres")]
        public string CPF { get; set; } = string.Empty;

        [DisplayName("Data de Nascimento")]
        [Required(ErrorMessage = "A data de nascimento é obrigatória")]
        public DateTime DataNascimento { get; set; } = DateTime.Now;

        [DisplayName("Perfil")]
        [Required(ErrorMessage = "O perfil é obrigatório")]
        [Range(1, 2, ErrorMessage = "Perfil inválido")]
        public int Perfil { get; set; } = 2; // 1 - Administrador, 2 - Usuário

        [DisplayName("Status")]
        public bool Status { get; set; } = true;

        public UsuarioViewModel()
        {
            
        }

        public UsuarioViewModel(Usuario usuario)
        {
            Nome = usuario.Nome;
            Email = usuario.Email;
            CPF = usuario.CPF;
            DataNascimento = usuario.DataNascimento;
            Perfil = usuario.Perfil;
            Status = usuario.Status;
        }
    }
}

CostManager/Controllers/UsuarioController.cs
using CostManager.Models.Database;
using CostManager.Models.Utils;
using CostManager.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CostManager.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class UsuarioController : Controller
    {
        private readonly dbCostManagerEntities db = new dbCostManagerEntities();
        private const int pageSize = 10;

        [HttpGet]
        public ActionResult Index(string nome, string email, string status, string perfil, int pagina = 1)
        {
            List<Usuario> usuarios = db.Usuario.ToList();

            if (!string.IsNullOrEmpty(nome))
                usuarios = usuarios.Where(u => u.Nome.Contains(nome)).ToList();

            if (!string.IsNullOrEmpty(email))
                usuarios = usuarios.Where(u => u.Email.Contains(email)).ToList();

            if (!string.IsNullOrEmpty(status))
            {
                bool Status = status == "1" ? true : false;
                usuarios = usuarios.Where(u => u.Status == Status).ToList();
            }

            if (!string.IsNullOrEmpty(perfil))
            {
                int Perfil = Convert.ToInt32(perfil);
                usuarios = usuarios.Where(u => u.Perfil == Perfil).ToList();
            }

            ViewBag.Nome = nome ?? string.Empty;
            ViewBag.Email = email ?? string.Empty;
            ViewBag.Status = status ?? string.Empty;
            ViewBag.Perfil = perfil ?? string.Empty;
            ViewBag.Pagina = pagina;
            ViewBag.TotalPaginas = Math.Ceiling((double)usuarios.Count / 10);

            return View(usuarios.Skip((pagina - 1) * pageSize).Take(pageSize));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new UsuarioViewModel());
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(UsuarioViewModel model)
        {
            if (model.Perfil > 0)
                ViewBag.Perfil = model.Perfil;

            if (!ModelState.IsValid)
                return View(model);

            if (db.Usuario.Any(u => u.CPF.ToLower() == model.CPF.ToLower()))
            {
                ModelState.AddModelError("CPF", "CPF já cadastrado.");
                return View(model);
            }

            if (db.Usuario.Any(u => u.Email.ToLower() == model.Email.ToLower()))
            {
                ModelState.AddModelError("Email", "E-mail já cadastrado.");
                return View(model);
            }

            Usuario usuario = new Usuario
            {
                Nome = model.Nome,
                CPF = model.CPF,
                DataNascimento = model.DataNascimento,
                Email = model.Email,
                Senha = Utils.GetMD5Hash(Utils.GenerateRandomPassword()),
                Perfil = model.Perfil,
                Status = model.Status
            };
            db.Usuario.Add(usuario);
            db.SaveChanges();

            TempData["Message"] = "Usuário cadastrado com sucesso.";

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            Usuario usuario = db.Usuario.Find(Id);

            if (usuario == null)
            {
                TempData["Message"] = "Usuário não encontrado.";
                return RedirectToAction(nameof(Index));
            }

            return View(new UsuarioViewModel(usuario));      
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(int Id, UsuarioViewModel model)
        {
            if (model.Perfil > 0)
                ViewBag.Perfil = model.Perfil;

            if (!ModelState.IsValid)
                return View(model);

            Usuario usuario = db.Usuario.Find(Id);

            if (usuario == null)
            {
                TempData["Message"] = "Usuário não encontrado.";
                return RedirectToAction(nameof(Index));
            }

            if (db.Usuario.Any(u => u.CPF.ToLower() == model.CPF.ToLower() && u.Id != Id))
            {
                ModelState.AddModelError("CPF", "CPF já cadastrado.");
                return View(model);
            }

            if (db.Usuario.Any(u => u.Email.ToLower() == model.Email.ToLower() && u.Id != Id))
            {
                ModelState.AddModelError("Email", "E-mail já cadastrado.");
                return View(model);
            }

            usuario.Nome = model.Nome;
            usuario.CPF = model.CPF;
            usuario.DataNascimento = model.DataNascimento;
            usuario.Email = model.Email;
            usuario.Perfil = model.Perfil;
            usuario.Status = model.Status;

            db.SaveChanges();

            TempData["Message"] = "Usuário alterado com sucesso.";

            return RedirectToAction(nameof(Index));
        }
    }
}

CostManager/Views/Usuario/Create.cshtml
@model CostManager.Models.ViewModel.UsuarioViewModel
@{
    ViewBag.Title = "Cadastro de usuário";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="mb-3">
    <div class="mb-5">
        <h3 class="text-uppercase fw-bold">@ViewBag.Title</h3>
    </div>

    <div class="mb-3">
        @using (Html.BeginForm("Create", "Usuario", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.Status);

            <div class="row mb-3">
                <div class="col-md-6">
                    @Html.LabelFor(x => x.Nome, new { @class = "form-label" })
                    @Html.EditorFor(x => x.Nome, new { htmlAttributes = new { @class = "form-control", @maxlength = "250" } })
                    @Html.ValidationMessageFor(x => x.Nome, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(x => x.Email, new { @class = "form-label" })
                    @Html.EditorFor(x => x.Email, new { htmlAttributes = new { @class = "form-control", @maxlength = "250" } })
                    @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row mb-5">
                <div class="col-md-4">
                    @Html.LabelFor(x => x.CPF, new { @class = "form-label" })
                    @Html.EditorFor(x => x.CPF, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.CPF, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(x => x.DataNascimento, new { @class = "form-label" })
                    @Html.EditorFor(x => x.DataNascimento, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                    @Html.ValidationMessageFor(x => x.DataNascimento, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(x => x.Perfil, new { @class = "form-label" })
                    <select class="form-select" name="Perfil" id="Perfil">
                        <option disabled selected>Selecione um perfil</option>
                        <option value="1" @(ViewBag.Perfil == "1" ? "selected" : string.Empty)>Administrador</option>
                        <option value="2" @(ViewBag.Perfil == "2" ? "selected" : string.Empty)>Usuário Geral</option>
                    </select>
                    @Html.ValidationMessageFor(x => x.Perfil, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="d-flex justify-content-end gap-2">
                <a href="@Url.Action("Index","Usuario")" class="btn btn-outline-secondary">
                    <i class="bi bi-arrow-left"></i>
                    Voltar
                </a>
                <button type="submit" class="btn btn-outline-success">
                    <i class="bi bi-plus-lg"></i>
                    Adicionar
                </button>
            </div>
        }
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#CPF").mask("000.000.000-00", { reverse: true });
        });
    </script>
}

CostManager/Views/Usuario/Edit.cshtml
@model CostManager.Models.ViewModel.UsuarioViewModel
@{
    ViewBag.Title = "Edição do Usuário";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="mb-3">
    <div class="mb-5">
        <h3 class="text-uppercase fw-bold">@ViewBag.Title</h3>
    </div>

    <div class="mb-3">
        @using (Html.BeginForm("Edit", "Usuario", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="row mb-3">
                <div class="col-md-6">
                    @Html.LabelFor(x => x.Nome, new { @class = "form-label" })
                    @Html.EditorFor(x => x.Nome, new { htmlAttributes = new { @class = "form-control", @maxlength = "250" } })
                    @Html.ValidationMessageFor(x => x.Nome, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-6">
                    @Html.LabelFor(x => x.Email, new { @class = "form-label" })
                    @Html.EditorFor(x => x.Email, new { htmlAttributes = new { @class = "form-control", @maxlength = "250" } })
                    @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row mb-5">
                <div class="col-md-4">
                    @Html.LabelFor(x => x.CPF, new { @class = "form-label" })
                    @Html.EditorFor(x => x.CPF, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(x => x.CPF, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(x => x.DataNascimento, new { @class = "form-label" })
                    <input type="date" name="DataNascimento" id="DataNascimento" class="form-control" value="@Model.DataNascimento.ToString("yyyy-MM-dd")" />
                    @Html.ValidationMessageFor(x => x.DataNascimento, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(x => x.Perfil, new { @class = "form-label" })
                    <select class="form-select" name="Perfil" id="Perfil">
                        <option disabled selected>Selecione um perfil</option>
                        <option value="1" @(Model.Perfil == 1 ? "selected" : string.Empty)>Administrador</option>
                        <option value="2" @(Model.Perfil == 2 ? "selected" : string.Empty)>Usuário Geral</option>
                    </select>
                    @Html.ValidationMessageFor(x => x.Perfil, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row mb-5">
                <div class="col-md-4">
                    <div class="form-check form-switch">
                        @Html.CheckBoxFor(x => x.Status, new { @class = "form-check-input", @role = "switch" })
                        @Html.LabelFor(x => x.Status, htmlAttributes: new { @class = "form-check-label" })
                    </div>
                    @Html.ValidationMessageFor(x => x.Status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="d-flex justify-content-end gap-2">
                <a href="@Url.Action("Index","Usuario")" class="btn btn-outline-secondary">
                    <i class="bi bi-arrow-left"></i>
                    Voltar
                </a>
                <button type="submit" class="btn btn-outline-success">
                    <i class="bi bi-floppy"></i>
                    Salvar
                </button>
            </div>
        }
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $("#CPF").mask("000.000.000-00", { reverse: true });
        });
    </script>
}

CostManager/Views/Usuario/Index.cshtml
@using CostManager.Models
@model IEnumerable<CostManager.Models.Database.Usuario>
@{
    ViewBag.Title = "Listagem de Usuários";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string message = TempData["Message"] as string ?? string.Empty;
}

<div class="mb-3">
    <div class="mb-4">
        <h3 class="text-uppercase fw-bold">@ViewBag.Title</h3>
    </div>

    @if (!string.IsNullOrEmpty(message))
    {
        <div class="mb-4">
            <div class="alert alert-@(message.ToUpper().Contains("SUCESSO") ? "success" : "danger") alert-dismissible fade show" role="alert">
                @message
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    }

    <div class="mb-4">
        @using (Html.BeginForm("Index", "Usuario", FormMethod.Get, new { enctype = "multipart/form-data" }))
        {
            <div class="row mb-4">
                <div class="col-md-3">
                    <label for="nome" class="form-label">Nome</label>
                    <input type="text" class="form-control" id="nome" name="nome" value="@ViewBag.Nome" autocomplete="off">
                </div>
                <div class="col-md-3">
                    <label for="email" class="form-label">E-mail</label>
                    <input type="text" class="form-control" id="email" name="email" value="@ViewBag.Email" autocomplete="off">
                </div>
                <div class="col-md-3">
                    <label for="perfil" class="form-label">Perfil</label>
                    <select id="perfil" name="perfil" class="form-select">
                        <option disabled selected>Todos</option>
                        <option value="1" @(ViewBag.Perfil == "1" ? "selected" : "")>Administrador</option>
                        <option value="2" @(ViewBag.Perfil == "2" ? "selected" : "")>Usuário</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <label for="status" class="form-label">Status</label>
                    <select id="status" name="status" class="form-select">
                        <option disabled selected>Todos</option>
                        <option value="1" @(ViewBag.Status == "1" ? "selected" : "")>Ativo</option>
                        <option value="2" @(ViewBag.Status == "0" ? "selected" : "")>Inativo</option>
                    </select>
                </div>
            </div>
            <div class="d-flex justify-content-between">
                <div>
                    <a href="@Url.Action("Create","Usuario")" class="btn btn-outline-success">
                        <i class="bi bi-plus-lg"></i>
                        Adicionar
                    </a>
                </div>
                <div class="d-flex justify-content-end gap-2">
                    <button type="button" id="cleanPage" class="btn btn-outline-danger">
                        <i class="bi bi-eraser-fill"></i>
                        Limpar
                    </button>
                    <button type="submit" class="btn btn-outline-info">
                        <i class="bi bi-search"></i>
                        Buscar
                    </button>
                </div>
            </div>
        }
    </div>

    @if (Model != null)
    {
        <div class="mb-4">
            <div class="table-responsive mb-3">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nome</th>
                            <th>E-mail</th>
                            <th>Perfil</th>
                            <th>Status</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Any())
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Nome</td>
                                    <td>@item.Email</td>
                                    <td>@PerfisExtensions.GetDescription(item.Perfil)</td>
                                    <td>
                                        @if (item.Status)
                                        {
                                            <i class="bi bi-check-circle-fill text-success"></i>
                                        }
                                        else
                                        {
                                            <i class="bi bi-x-circle-fill text-danger"></i>
                                        }
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "Usuario", new { Id = item.Id })" title="Edit">
                                            <i class="bi bi-pencil-square"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="6" class="text-center">Nenhum registro encontrado</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

        if (ViewBag.TotalPaginas > 0)
        {
            <div class="mb-3">
                <ul class="pagination justify-content-end">
                    @if (ViewBag.Pagina > 1)
                    {
                        <li class="page-item">
                            <a class="page-link" href="@Url.Action("Index", "Usuario", new { nome = ViewBag.Nome, email = ViewBag.Email, status = ViewBag.Status, perfil = ViewBag.Perfil, pagina = ViewBag.Pagina - 1 })">&laquo;</a>
                        </li>
                    }
                    <li class="page-item page-link">Página @ViewBag.Pagina de @ViewBag.TotalPaginas</li>
                    @if (ViewBag.Pagina < ViewBag.TotalPaginas)
                    {
                        <li class="page-item">
                            <a class="page-link" href="@Url.Action("Index", "Usuario", new { nome = ViewBag.Nome, email = ViewBag.Email, status = ViewBag.Status, perfil = ViewBag.Perfil, pagina = ViewBag.Pagina + 1 })">&raquo;</a>
                        </li>
                    }
                </ul>
            </div>
        }


    }
</div>


@section Scripts {
    <script>
        $(document).ready(function () {
            $("#cleanPage").click(function() {
                window.location.href = "@Url.Action("Index", "Usuario")";
            })
        })
    </script>
}